baseURL = 'https://github.com/lakfel/jfelipegonzalez.git'
languageCode = 'en-us'
title = 'J. Felipe Gonzalez, Ph.D.'
paginate = 3
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/imgJFGA.jpg'
  description = "A minimal hugo theme focus on content"
  author = 'Calvin Tran'

  [params.comments]
    enabled = true
    githubRepo = 'canhtran/maverick'
    theme = 'github-light'


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = "-210"
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = "-170"
  [[menu.main]]
    identifier = "posts"
    name = "Post"
    url = "/posts/"
    weight = -100

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
